version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  noorbs-test-currents-image:
    parallelism: 3
    docker:
      - image: currents/cypress-included:12.17.4
    steps:
      - checkout
      - run: npx cypress-cloud run --parallel --record --key $CURRENTS_RECORD_KEY

  noorbs-test-explicit-download:
    parallelism: 3
    docker:
      - image: cypress/base:18.16.1
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: CYPRESS_DOWNLOAD_MIRROR=https://cy-cdn.currents.dev npx cypress install --force
      - run: npx cypress-cloud run --parallel --record --key $CURRENTS_RECORD_KEY

  cypress-install:
    executor: cypress/default
    steps:
      - cypress/install:
          post-install: CYPRESS_DOWNLOAD_MIRROR=https://cy-cdn.currents.dev npx cypress install --force

  cypress-run:
    executor: cypress/default
    parallelism: 3
    steps:
      - cypress/run-tests:
          cypress-command: npx cypress-cloud run --parallel --record --key $CURRENTS_RECORD_KEY

workflows:
  noorbs:
    jobs:
      - noorbs-test-currents-image:
          context: currents
      - noorbs-test-explicit-download:
          context: currents
  with-orbs:
    jobs:
      - cypress-install
      - cypress-run:
          context: currents
          requires:
            - cypress-install
