version: 2.1

jobs:
  test:
    parallelism: 3
    docker:
      - image: cypress/base:18
    steps:
      - checkout
      - run: DEBUG=currents:* npx cypress-cloud run --parallel --record --key $CURRENTS_RECORD_KEY
workflows:
  cypress:
    jobs:
      - test:
          context: currents
