version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  cypress-run:
    executor:
      docker:
        image: currents/cypress-included:12.17.4
    parallelism: 3
    steps:
      - cypress/run-tests:
          cypress-command: npx cypress-cloud run --parallel --record --key $CURRENTS_RECORD_KEY

workflows:
  build:
    jobs:
      - cypress-run:
          context: currents
