version: 2.1

jobs:
  test:
    parallelism: 3
    docker:
      - image: currents/cypress-included:12.17.4
    steps:
      - checkout
      - run: npx cypress-cloud run --parallel --record --key $CURRENTS_RECORD_KEY
workflows:
  cypress:
    jobs:
      - test:
          context: currents
